version: "3.9"

services:
  report-back-fast-api:
    image: report-back-fast-api:1.0.0
    container_name: report-back-fast-api
    ports:
      - "127.0.0.1:8001:8000"
    env_file:
      - .env
    restart: unless-stopped
